module.exports = {
  blogName: "Fossbook Comics",
  authorName: "Fossbook",
  authorDescription: "A Markdown-first publishing tool for comic creators.",
  authorWebsite: "https://github.com/joone/fossbook",
  blogDescription:
    "A comic tour of Fossbook: author, preview, and publish illustrated stories with Markdown.",
  blogsite: "https://joone.github.io/fossbook",
  githubRepository: "https://github.com/joone/fossbook",
  image: "https://joone.github.io/fossbook/images/fossbook-comic-authoring.png",
  theme: "archie",
  defaultLanguage: "en",
  defaultLanguageInSubdir: false,
  languages: {
    en: { languageName: "English", locale: "en-US" },
    ko: { languageName: "한국어", locale: "ko-KR" },
  },
  basePath: "/fossbook/",
  postsPath: "posts",
  content: "./content",
  postsDir: "./content/posts",
  outputDir: "./public",
  staticDir: "./static",
  themesDir: "./themes",
};
